services:
  app:
    tty: true
    stdin_open: true
    networks:
      - app_network
    build:
      context: .
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./:/app
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15
    hostname: db
    env_file:
      - ./.env
    networks:
      - app_network
    environment:
      - TZ=Asia/Tokyo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

networks:
  app_network:
    driver: bridge
volumes:
  node_modules:
  db_data:
